/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const Time = IDL.Int;
export const BrandId = IDL.Nat;
export const Price = IDL.Int;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'addedOn' : Time,
  'brandId' : BrandId,
  'category' : IDL.Text,
  'pricePkr' : Price,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DeliveryAddress = IDL.Record({
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'postal' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'cashOnDelivery' : IDL.Null,
  'onlineCard' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const ClaimAdminResult = IDL.Variant({
  'alreadyExists' : IDL.Null,
  'anonymousCaller' : IDL.Null,
  'success' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'totalPkr' : Price,
  'quantity' : IDL.Nat,
  'pricePkr' : Price,
  'product' : Product,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddress,
  'paymentMethod' : PaymentMethod,
  'user' : IDL.Principal,
  'totalAmountPkr' : Price,
  'timestamp' : Time,
  'items' : IDL.Vec(OrderItem),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const Cart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
export const TransferAdminResult = IDL.Variant({
  'authenticationError' : IDL.Null,
  'anonymousCaller' : IDL.Null,
  'success' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [ProductId], []),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkout' : IDL.Func([DeliveryAddress, PaymentMethod], [OrderId], []),
  'claimAdminRole' : IDL.Func([], [ClaimAdminResult], []),
  'clearCart' : IDL.Func([], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getOrder' : IDL.Func([OrderId], [Order], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transferAdminRole' : IDL.Func([], [TransferAdminResult], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateProduct' : IDL.Func([ProductId, Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const Time = IDL.Int;
  const BrandId = IDL.Nat;
  const Price = IDL.Int;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'addedOn' : Time,
    'brandId' : BrandId,
    'category' : IDL.Text,
    'pricePkr' : Price,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DeliveryAddress = IDL.Record({
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'postal' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'cashOnDelivery' : IDL.Null,
    'onlineCard' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const ClaimAdminResult = IDL.Variant({
    'alreadyExists' : IDL.Null,
    'anonymousCaller' : IDL.Null,
    'success' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'totalPkr' : Price,
    'quantity' : IDL.Nat,
    'pricePkr' : Price,
    'product' : Product,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'deliveryAddress' : DeliveryAddress,
    'paymentMethod' : PaymentMethod,
    'user' : IDL.Principal,
    'totalAmountPkr' : Price,
    'timestamp' : Time,
    'items' : IDL.Vec(OrderItem),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const Cart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
  const TransferAdminResult = IDL.Variant({
    'authenticationError' : IDL.Null,
    'anonymousCaller' : IDL.Null,
    'success' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [ProductId], []),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkout' : IDL.Func([DeliveryAddress, PaymentMethod], [OrderId], []),
    'claimAdminRole' : IDL.Func([], [ClaimAdminResult], []),
    'clearCart' : IDL.Func([], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getOrder' : IDL.Func([OrderId], [Order], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transferAdminRole' : IDL.Func([], [TransferAdminResult], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateProduct' : IDL.Func([ProductId, Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };