/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BrandId = bigint;
export interface Cart { 'items' : Array<CartItem> }
export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export type ClaimAdminResult = { 'alreadyExists' : null } |
  { 'anonymousCaller' : null } |
  { 'success' : null };
export interface DeliveryAddress {
  'street' : string,
  'country' : string,
  'city' : string,
  'name' : string,
  'phone' : string,
  'postal' : string,
}
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddress,
  'paymentMethod' : PaymentMethod,
  'user' : Principal,
  'totalAmountPkr' : Price,
  'timestamp' : Time,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'totalPkr' : Price,
  'quantity' : bigint,
  'pricePkr' : Price,
  'product' : Product,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null };
export type PaymentMethod = { 'cashOnDelivery' : null } |
  { 'onlineCard' : null };
export type Price = bigint;
export interface Product {
  'id' : ProductId,
  'name' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'addedOn' : Time,
  'brandId' : BrandId,
  'category' : string,
  'pricePkr' : Price,
}
export type ProductId = bigint;
export type Time = bigint;
export type TransferAdminResult = { 'authenticationError' : null } |
  { 'anonymousCaller' : null } |
  { 'success' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], ProductId>,
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkout' : ActorMethod<[DeliveryAddress, PaymentMethod], OrderId>,
  'claimAdminRole' : ActorMethod<[], ClaimAdminResult>,
  'clearCart' : ActorMethod<[], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transferAdminRole' : ActorMethod<[], TransferAdminResult>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[ProductId, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];